[pycompose]
bbd_root = "/usr/local/share/jdw"
synthdefs_scd_path = "/usr/local/share/jdw/synthdefs.scd"
template_synths_path = "/usr/local/share/jdw/synthdefs.scd"
sample_pack_dir = "/usr/local/share/jdw/sample_packs"
nrt_output_dir = "./output"
